export const prompt = "Your task is to answer questions correctly. You have access to a Javascript interpreter, so if you are not able to answer a question from memory, you can write a program that will answer the question. Always write your answer as a valid Javascript program, with helpful comments.\n\nBegin.\n\nQuestion: What is 37593 * 67?\nAnswer:\n```\n// Multiply the numbers\n(37593 * 67)\n```\n\nQuestion: What is the id of Github user aneesha99?\nAnswer:\n```\nconst APIResponse = await fetch('https://api.github.com/users/aneesha99');\nconst gitHubUser = await APIResponse.json();\n(gitHubUser.login)\n```\n\nQuestion: What year was the American president George Washington born?\nAnswer:\n```\n(1732)\n```\n";

//export const colorPrompt = "Your task is to answer questions correctly. Always write your answer as a comma separated list of four hex values. Try to choose a variety of differen colors that still work together.\n\nBegin.\n\nQuestion: What are four different colors that belong together in a room that can be described as 'bright and open'?\nAnswer:\n```0x94FFEB, 0xFFE2A2, 0xFBC3BC, 0xFFFFFF```\n\nQuestion: What are four different colors that belong together in a room that can be described as 'cozy and rustic'?\nAnswer:\n```0xEC9E49, 0xB6574B, 0xC65733, 0x360D0D```\n\nQuestion: What are four different colors that belong together in a room that can be described as 'modern and sleek'?\nAnswer:\n```0xFFFEFB, 0x7BD0CD, 0x29403B, 0x000000```\n";

export const colorPrompt = "Your task is to answer questions correctly. Always write your answer as a comma separated list of five hex values. Choose a variety of different colors that still work together, not just shades of the same color.\n\nBegin.\n\nQuestion: What are five different colors that belong together in a room that can be described as 'bright and open'?\nAnswer:\n```0x94FFEB, 0xFFE2A2, 0xFBC3BC, 0xBFECBF, 0xFFFFFF```\n\nQuestion: What are five different colors that belong together in a room that can be described as 'cozy and rustic'?\nAnswer:\n```0xEC9E49, 0xB6574B, 0xC65733, 0x360D0D, 0x75B078```\n\nQuestion: What are five different colors that belong together in a room that can be described as 'modern and sleek'?\nAnswer:\n```0xFFFEFB, 0x7BD0CD, 0x29403B, 0x000000, 0x081044```\n";

//export const tablePrompt = "Your task is to answer questions correctly. The options to answer the questions are  Always write your answer as a comma separated list of numbers.\n\nBegin.\n\nQuestion: What type of table best suits a room that can be described as '";

export const furnitureColor = "Your task is to answer questions correctly. Always write your answer as a comma separated list of furniture items followed by a hex value. Allowed hex values will be given in each question and a hex value can be used more than once.\n\nBegin.\n\nQuestion: What colors best suits a table, bed, chair, shelf, couch, wall hanging, and walls of a room that can be described as 'bright and open'? Allowed colors are 0x94FFEB, 0xFFE2A2, 0xFBC3BC, 0xBFECBF, 0xFFFFFF\nAnswer:\n```table: 0x94FFEB, bed: 0xFFE2A2, chair: 0x94FFEB, shelf: 0xBFECBF, couch: 0xFBC3BC, wall hanging: 0x0xFFE2A2, walls: 0xFFFFFF```\n\nQuestion: What colors best suits a table, bed, chair, shelf, couch, wall hanging, and walls of a room that can be described as 'cozy and rustic'? Allowed colors are 0xEC9E49, 0xB6574B, 0xC65733, 0x360D0D, 0x75B078\nAnswer:\n```table: 0xEC9E49, bed: 0x360D0D, chair: 0xC65733, shelf:0x75B078, couch: 0xEC9E49, wall hanging: 0x360D0D, walls: 0xB6574B```\n\nQuestion: What colors best suits a table, bed, chair, shelf, couch, wall hanging, and walls of a room that can be described as 'modern and sleek'? Allowed colors are 0xFFFEFB, 0x7BD0CD, 0x29403B, 0x000000, 0x081044\nAnswer:\n```table: 0x29403B, bed: 0x7BD0CD, chair: 0x29403B, shelf: 0x000000, couch: 0x29403B, wall hanging: 0x081044, walls: 0x7BD0CD```\n";

// Prompt with more furniture types if there is time
//export const furnitureType = "Your task is to find a furniture type from the allowed options that best match the characteristics of the input phrase. Always write your answer as a comma separated list of furniture labels followed by a specific item.\n\nBegin.\n\nQuestion: What type of couch best suits a room that can be described as 'bright and open'? Allowed types are 'minimalist curved couch with armrest on one side', 'beanbag', 'ottoman', 'cabriole couch'. What type of table best suits a room that can be described as 'bright and open'? Allowed types are 'basic plain wooden desk', 'round wooden table', 'vanity table'. What type of bed best suits a room that can be described as 'bright and open'? Allowed types are 'standard plain bed', 'ornate bed' and 'platform bed'. What type of wall hangings best suits a room that can be described as 'bright and open'? Allowed types are 'bookshelf', 'postcards', 'oil painting with ornate gold frame', 'macrame tapestry'. What type of chair best suits a room that can be described as 'bright and open'? Allowed types are 'plain wooden chair', 'armchair', 'ornate chair'. What type of shelf best suits a room that can be described as 'bright and open'? Allowed types are 'dark wooden cabinets', 'steel frame shelves', 'light wooden display shelf'.\nAnswer:\n```couch: beanbag, table: round wooden table, bed: platform bed, wall hangings: oil painting with ornate gold frame, chair: armchair, shelf: light wooden display shelf```";

export const furnitureType = "Your task is to find a furniture type from the allowed options that best match the characteristics of the input phrase. Always write your answer as a comma separated list of furniture labels followed by a specific item.\n\nBegin.\n\nQuestion: What type of couch best suits a room that can be described as 'bright and open'? Allowed types are 'beanbag', 'ottoman'. What type of table best suits a room that can be described as 'bright and open'? Allowed types are 'basic plain wooden desk', 'round wooden table'. What type of bed best suits a room that can be described as 'bright and open'? Allowed types are 'standard plain bed'. What type of wall hangings best suits a room that can be described as 'bright and open'? Allowed types are 'bookshelf', 'postcards', 'oil painting with ornate gold frame', 'macrame tapestry'. What type of chair best suits a room that can be described as 'bright and open'? Allowed types are 'plain wooden chair', 'armchair'. What type of shelf best suits a room that can be described as 'bright and open'? Allowed types are 'dark wooden cabinets', 'steel frame shelves', 'light wooden display shelf'.\nAnswer:\n```couch: beanbag, table: round wooden table, bed: standard plain bed, wall hangings: oil painting with ornate gold frame, chair: armchair, shelf: light wooden display shelf```";